# Do: title, toc:table-of-contents ::fixed-width-sections |tables Do: ^:sup/sub
# with curly -:special-strings *:emphasis
# Don't: prop:no-prop-drawers \n:preserve-linebreaks ':use-smart-quotes
#+OPTIONS: prop:nil title:t toc:t \n:nil ::t |:t ^:{} -:t *:t ':nil
# vim: set textwidth=69

#+RFC_CATEGORY: std
#+RFC_NAME: draft-ietf-ipsecme-ikev2-beet-mode
#+RFC_VERSION: 05
#+RFC_IPR: trust200902
#+RFC_STREAM: IETF
#+RFC_TOC_DEPTH: 4
#+RFC_XML_VERSION: 3
#+RFC_CONSENSUS: true

#+TITLE: IKEv2 negotiation for Bound End-to-End Tunnel (BEET) mode ESP
#+RFC_SHORT_TITLE: IKEv2 for BEET mode ESP
#+AUTHOR: Antony Antony
#+EMAIL: antony.antony@secunet.com
#+AFFILIATION: secunet Security Networks AG
#+RFC_SHORT_ORG: secunet
#+RFC_ADD_AUTHOR: ("Steffen Klassert" "steffen.klassert@secunet.com" ("secunet" "secunet Security Networks AG"))
#+RFC_AREA: sec
#+RFC_WORKGROUP: IPSECME Working Group

#+begin_abstract
This document specifies a new Notify Message Type Payload for the
Internet Key Exchange Protocol Version 2 (IKEv2), to negotiate IPsec
ESP Bound End-to-End Tunnel (BEET) mode. BEET mode combines the
benefits of tunnel mode with reduced overhead, making it suitable for
applications requiring minimalistic end-to-end tunnels, mobility
support, and multi-address multi-homing capabilities. The
introduction of the USE_BEET_MODE Notify Message enables the
negotiation and establishment of BEET mode security associations.

#+end_abstract
#+RFC_KEYWORDS: ("IKEv2" "BEET")

* Introduction

The Bound End-to-End Tunnel (BEET) mode is specified in
[[I-D.ipsecme-rfc7402-beet-update]]. BEET mode was
originally proposed in [[I-D.nikander-esp-beet-mode]] and first
standardized in Appendix B of [[RFC7402]]. It offers an optimized
approach for deploying IP Security (IPsec) [[RFC4301]] using
Encapsulating Security Payload (ESP) [[RFC4303]] for end-to-end use
cases. It combines the advantages of Tunnel and Transport modes
specified in [[RFC7296]], while minimizing their overhead for
end-to-end use cases.

This document specifies the necessary code points to negotiate an
ESP BEET mode SA using the Internet Key Exchange Protocol Version 2
(IKEv2) [RFC7296], by introducing a new Notify Message Status Type,
USE_BEET_MODE, to facilitate the negotiation and establishment of
BEET mode security associations in IKEv2.


** Background

For over a decade, a minimalist IPsec tunnel mode, BEET, has been in
use for end-to-end security in HIP environments without IKE
negotiation, [[RFC7401]]. Also, in many environments,  with IKE negotiation
using a private IKEv2 Notify Message Status Type (strongSWAN).

Additionally, BEET mode ESP is valuable for low-power devices which
usually use only one end-to-end IPsec tunnel, as it reduces power
consumption [[RFC9333]]and complexity. In situations where devices or
IPsec connections are dedicated to a single application or transport
protocol, the use of BEET mode simplifies packet processing and
conserves energy, especially benefiting lower-powered devices.


** Requirements Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in
BCP 14 [[RFC2119]] [[RFC8174]] when, and only when, they appear in
all capitals, as shown here.


* IKEv2 Negotiation

When negotiating a Child SA using IKEv2, the new "USE_BEET_MODE"
Notify Message Status Type is used to negotiate BEET mode for the
Child SA pair. The method used is similar to how USE_TRANSPORT_MODE is
negotiated, as described in [[RFC7296]]

To request a BEET-mode SA on the Child SA pair, the initiator MUST
include the USE_BEET_MODE, Notify Message Status Type, when requesting
a new Child SA, either during the IKE_AUTH or the CREATE_CHILD_SA
exchanges to create a new Child SA. If the request is accepted, the
response MUST also include a USE_BEET_MODE Notification Message Status
Type. If the responder declines and does not include the USE_BEET_MODE
notification in the response, the Child SA will be established in
Tunnel mode. If Tunnel mode is unacceptable to the initiator, the
initiator MUST delete the Child SA via a subsequent INFORMATIONAL
exchange with a Delete payload, as specified in [[RFC7296]].

A responder for which Tunnel mode is not an acceptable fallback for
this Child SA MAY, during a CREATE_CHILD_SA exchange, instead reject
the request by returning a NO_PROPOSAL_CHOSEN notification, in which
case no Child SA is created. During the IKE_AUTH exchange, the
responder MUST instead follow the Tunnel-mode fallback described
above, since rejecting the Child SA via NO_PROPOSAL_CHOSEN would
leave the IKE SA established without any Child SA.

When rekeying a Child SA that was established with BEET mode, the
USE_BEET_MODE notification MUST NOT be included in the CREATE_CHILD_SA
exchange; the mode of the replacement Child SA is inherited from the
Child SA being replaced.

The USE_BEET_MODE notification MUST NOT be combined with other Child
SA mode notifications, such as USE_TRANSPORT_MODE or USE_AGGFRAG
[[RFC9347]], in the same request. As BEET mode is currently specified
only in terms of Tunnel mode processing
[[I-D.ipsecme-rfc7402-beet-update]], its interaction with these other
modes is not defined.

If a responder nonetheless receives a request containing the
USE_BEET_MODE notification together with one or more other Child SA
mode notifications, it MUST select at most one of these notifications,
or none of them -- in which case the Child SA is established in Tunnel
mode -- and include only that single notification, if any, in its
response.

If, contrary to the above, the response includes the USE_BEET_MODE
notification together with any other Child SA mode notification, the
response is ambiguous as to which mode the responder has selected;
the initiator MUST treat the
response as invalid and MUST delete the Child SA. In either case --
whether the responder omitted USE_BEET_MODE (resulting in Tunnel
mode, as described above) or returned such an ambiguous response --
the initiator can determine acceptability immediately upon processing
the response. It MAY therefore delete the Child SA without first
installing it.


** Traffic Selectors

A BEET mode Security Association binds the Child SA to a single,
fixed pair of inner addresses for its lifetime
[[I-D.ipsecme-rfc7402-beet-update]]. This is in contrast to Tunnel
mode, where the Traffic Selectors negotiate address ranges and the
inner addresses of any given packet may be any pair of addresses
within those ranges. For this reason, the Traffic Selectors (TSi and
TSr) of a Child SA negotiated with the USE_BEET_MODE notification
MUST each specify a single IP address -- that is, a Starting Address
equal to the Ending Address (equivalent to a /32 or /128 prefix), as
defined in Section 3.13.1 of [[RFC7296]] -- which become the inner
addresses bound to the Child SA.

The initiator MAY propose TSi and TSr that already each specify a
single IP address, or MAY propose broader Traffic Selectors and rely
on the responder to narrow them, as described in Section 2.9 of
[[RFC7296]]. If the responder selects USE_BEET_MODE, the TSi and TSr
returned in its response MUST each specify a single IP address,
regardless of how the corresponding Traffic Selectors were proposed
in the request. If the proposed Traffic Selectors cannot be narrowed
to a single address acceptable to the responder's policy, the
responder MUST NOT include the USE_BEET_MODE notification in its
response, resulting in Tunnel mode (or NO_PROPOSAL_CHOSEN, per the
responder's policy as described above).

The initiator MUST verify that, when the response includes the
USE_BEET_MODE notification, the TSi and TSr returned in the response
each specify a single IP address. If they do not, the response is
invalid; as with an ambiguous USE_BEET_MODE response described above,
the initiator MUST delete the Child SA.


** USE_BEET_MODE Notify Message Payload

The USE_BEET_MODE Notify Message Status Type uses the Notify Payload
format defined in Section 3.10 of [[RFC7296]]. The Protocol ID and SPI Size fields
MUST be set to 0 and MUST be ignored if not 0. The notification
carries no Notification Data.


* IANA Considerations


This document defines a new "IKEv2 Notify Message Status Type" to be
added to the IANA registry [[STATUSNOTIFY]]

#+name: iana_requests_i
#+begin_src


      Value   Notify Message Status Type     Reference
      -----   ---------------------------    ---------------
      [TBD1]   USE_BEET_MODE                  [this document]


#+end_src

* Security Considerations

In this section we discuss the security properties of the BEET mode,
discussing some and point out some of its limitations [[RFC3552]].

There are no known new vulnerabilities that the addition of the BEET
mode to IKEv2 would create.

Since the BEET security associations have the semantics of a fixed,
point-to-point tunnel between two IP addresses, it is possible to
place one or both of the tunnel end points into other network or
nodes but those that actually "possess" the inner IP addresses, i.e.,
to implement a BEET mode proxy. However, since such usage defeats the
security benefits of combined ESP processing, as discussed in
[[I-D.nikander-esp-beet-mode]], the implementations SHOULD NOT
support such usage when used in combination with IKEv2; instead use IKEv2
MOBIKE to move the between networks.

Falling back to Tunnel mode when USE_BEET_MODE is not negotiated is
functionally complete in most deployments, at the cost of the
header-compression and address-mapping optimizations BEET mode
provides. In some use cases, however -- such as Host Identity
Protocol (HIP) deployments [[RFC7401]] that rely on these address
mappings -- the fallback may result in a loss of functionality
beyond these optimizations. Whether such a loss is acceptable for a
given deployment is outside the scope of IKEv2 negotiation.


* Implementation Status

[Note to RFC Editor: Please remove this section and the reference to
[[RFC6982]]before publication.]

This section records the status of known implementations of the
protocol defined by this specification at the time of posting of this
Internet-Draft, and is based on a proposal described in [[RFC7942]].
The description of implementations in this section is intended to
assist the IETF in its decision processes in progressing drafts to
RFCs. Please note that the listing of any individual implementation
here does not imply endorsement by the IETF. Furthermore, no effort
has been spent to verify the information presented here that was
supplied by IETF contributors. This is not intended as, and must not
be construed to be, a catalog of available implementations or their
features. Readers are advised to note that other implementations may
exist.

According to [[RFC7942]], "this will allow reviewers and working
groups to assign due consideration to documents that have the benefit
of running code, which may serve as evidence of valuable
experimentation and feedback that have made the implemented protocols
more mature. It is up to the individual working groups to use this
information as they see fit".

Authors are requested to add a note to the RFC Editor at the top of
this section, advising the Editor to remove the entire section before
publication, as well as the reference to [[RFC7942]].


** Linux XFRM

Linux


- Organization: :: Linux kernel Project
- Name: :: Linux Kernel https://www.kernel.org/
- Description: :: Implements BEET mode in ESP. The initial support was added in 2006.
  It is widely used
- Level of maturity: :: Stable and used for over 15 years
- Licensing: :: GPLv2
- Implementation experience: :: There is no support for IPv4 fragments yet. IPv6 fragments appears to
  work. The BEET mode code is in production for over a decade. And it
  appears stable.
- Contact: :: https://lore.kernel.org/netdev/


** strongSwan


- Organization: :: The strongSwan Project
- Name: :: strongSwan
  https://docs.strongswan.org/docs/5.9/swanctl/swanctlConf.html
- Description: :: Implements IKE negotiation and ESP support for BEET mode Linux
- Level of maturity: :: Stable for a long time
- Coverage: :: Implements negotiating BEET mode support in Child SA negotiations and
  using it in ESP. The initial support was added in 2006.  Does not support IPv4
  fragments yet. IPv6 fragments appears to work.
- Licensing: :: GPLv2
- Implementation experience :: strongSwan use a private Notify Message Status Type USE_BEET_MODE
  (40961) for IKE. As far we know BEET is widely used.
- Contact :: Tobias Brunner tobias@strongswan.org


** iproute2


- Organization: :: The iproute2 Project
- Name: :: iproute2 https://git.kernel.org/pub/scm/network/iproute2/iproute2.git
- Description: :: Implements BEET mode support in ESP. e.g. command support "ip xfrm
  policy ... mode beet" . and "ip xfrm state .. mode beet". The
  initial support was added in 2006
- Level of maturity: :: Stable
- Licensing: :: GPLv2
- Implementation experience: :: TBD
- Contact: :: https://lore.kernel.org/netdev/ or Stephen Hemminger
  stephen@networkplumber.org


* Acknowledgments

We extend our sincere gratitude to the authors and contributors who
contributed to the standardization of BEET mode. Their insights and
dedication have significantly influenced our work, as well as their
contributions to the implementation of BEET mode many years ago.


* Normative References

** RFC2119
** RFC8174
** RFC7296
** I-D.ipsecme-rfc7402-beet-update

* Informative References

** RFC3552
** RFC6982
** RFC7402
** RFC7942
** RFC7401
** RFC9333
** RFC9347
** RFC4301
** RFC4303
** I-D.nikander-esp-beet-mode

** STATUSNOTIFY
:PROPERTIES:
:REF_TARGET: https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters.xhtml#ikev2-parameters-16
:REF_TITLE: IKEv2 Notify Message Status Types
:REF_ORG: IANA
:END:

